########################################################
# Training parameters
########################################################
# Batch size for train and eval
per_device_train_batch_size: 64 #4
per_device_eval_batch_size: 64 #4
# Number of training epochs
num_train_epochs: 2 #128
# Number of training steps( overrides num_epochs)
#max_steps: null
# Parameters related to the push-forward trick during training
pushforward_config: #null
  # At which training step to introduce next unroll stage
  deciding_epochs: [-1, 2, 50]
  # For how many steps to unroll
  max_allowed_unroll_steps: [0, 1, 2]
  # Which probability ratio to keep between the unrolls
  relative_probabilities: [7, 2, 1]
#To use mix precison training set fp16 to true
fp16: false
#number of workers for dataloader
dataloader_num_workers: 0 
########################################################
# Evaluation parameters
########################################################
# % of train.h5 dataset used for evaluation
# Number of steps to accumulate predictions on GPU before moving to CPU
eval_accumulation_steps: 16
# Ratio of train.h5 dataset used for evaluation
eval_split_ratio: 0.2
#metric for best model
metric_for_best_model: "l2_error"
# Number of rollouts to use for evaluation
n_eval_rollouts: 4
# Plot after epochs, note that plotting will be done continously after this epoch.
plot_after_epoch: null #[0.05, 0.1] or 0.05
# Number of examples to plot
n_plot_examples: 1

