# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: 2D_SABW_SSOO
dataset_directory_path: ./data/<path_to_folder_containing_train.h5_and_test.h5>
seed: 42
dimension: 2
grid_resolution: null
eval_groups: null
is_steady_state_prediction: False 
sequence_info: [4, 1, 10]
# Available channels for Shock_Bubble: ["density", "density_1", "density_2", "pressure", "diffuse_volume_fraction_1", "velocityX", "velocityY"]
# density_1 is the phasic density of the air bubble and density_2 is the phasic density of water
filter_features:
  train_filter_frames: null
  train_filter_groups: null
  infer_filter_frames: null
  infer_filter_groups: null
  filter_in_channels: null
  filter_out_channels: null
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
conditioning_features:
  conditioning_in_channels: null #support deprecated, please keep to null
  conditioning_method: null #AdaNorm # AdaNorm_LSE, AdaNorm_SE_per_param, AdaNorm_1SE, AdaNorm and null
  conditioning_parameter_names: null
  parameter_min_max_stats: null
  conditioning_mlp:
    mlp: False
    hidden_size: null
    activation: gelu
    initialization: null
residual_config: null #experimental
coord_features: True #appends x and y normalized coordinate grid to the fields/channels
data_normalization_strategy: z_normalization
log_transform_channels: ["density"] #include the statistics for the log-transformed channels
#Note: Statistics are for 256x256 grid resolution.
data_normalization_stats: 
  density:
    mean: 1111.2328262267508
    std: 220.3226082209927
    min: 1.0264859121380934e-05
    max: 1931.9257916170393
  density_1:
    mean: 1114.4805457128864
    std: 211.96941806055622
    min: 0.0
    max: 1931.9257916170393
  density_2:
    mean: 0.5496072121248086
    std: 9.262301190666449
    min: 0.0
    max: 1009.7616890589902
  diffuse_volume_fraction_1:
    mean: 0.9821301347654935
    std: 0.13034713827232858
    min: 0.0
    max: 1.0
  pressure:
    mean: 893698182.2081798
    std: 1276908095.8269563
    min: -428178596.7338052
    max: 20179237618.677658
  velocityX:
    mean: 330.7206668406086
    std: 432.3271661821583
    min: -6806.082142563164
    max: 10226.292559923522
  velocityY:
    mean: -0.13745771990594402
    std: 116.4204948235203
    min: -10370.648087517484
    max: 8979.373996552808
  log_density:
    mean: 6.906805091173552
    std: 0.881164879519018
    min: -11.48678423175892
    max: 7.566272603898667