model_name: DeepONet_ResNet
branch_depth: 2 #4
trunk_depth: 2 #4
padding: 1
latent_channels: 2 #32
width: 2 #128
ResNet_block: "BasicBlockND4DeepONet"
activation_fn_name: "ReLU"
num_blocks: [1,1,1,1] #blocks are as a list as different resnet blocks can be potentially combined.