model_name: ScOT3D
patch_size: [2, 4, 4] # patch embedding resolution: resolution/patch_size -> padding if not divisible
latent_channels: 27
depths: [2, 4, 2] # ~1M parameters
num_heads: [3, 6, 12]
skip_connections: [2, 2, 0]
window_size: [2, 7, 7] # (window_size - patch_embedding_resolution % window_size) % window_size -> padding before window-based self-attention
mlp_ratio: 2.0
qkv_bias: True
hidden_dropout_prob: 0.0
attention_dropout_prob: 0.0
drop_path_rate: 0.0
hidden_act: "gelu"
use_absolute_embeddings: False # Position embedding in ScOTEmbedding (learnable parameter)
initializer_range: 0.02
residual_model: "convnext" # convnext or resnet
norm_layer_eps: 1e-5
norm: 'layer' # layer, batch, group (see model_utils.py for max_groups), identity