logging: 
  output_dir: null
  checkpoint_prefix: "2" # Optional prefix for checkpoints directory, should be a string
  wandb: False
  wandb_project: 'test-project'
  wandb_run_name: null
  disable_progress_bar: True
  wandb_api_key: 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
  wandb_offline: False
  # if wandb is already setup and logged into the machine, then api key is obtained as follows:
  # python -c "import wandb; print(wandb.Api().api_key)"