# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: KuramotoSivashinsky
seed: 42
dataset_directory_path: ./data/fluids/KS/1D
dimension: 1
grid_resolution: null
eval_groups: ["seed 000000"]
is_steady_state_prediction: False
sequence_info: [4, 3, 1]
# available channels for KS: ['velocity']
filter_features:
  train_filter_frames: null
  train_filter_groups: null
  infer_filter_frames: null
  infer_filter_groups: null
  filter_in_channels: null
  filter_out_channels: null
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
conditioning_features:
  conditioning_in_channels: null
  include_conditioning_parameters: False
  num_cond_params: null
  parameter_min_max_stats: null
residual_config: null
  # add_base_value_with_raw_loss: False
  # add_predicted_value_with_diff_loss: True
  # add_predicted_value_with_raw_loss: False
coord_features: True
data_normalization_strategy: z_normalization
data_normalization_stats:
  velocity:
    mean: 1.4921739360114074e-07
    std: 0.33965544523545554
    min: -0.9674431085586548
    max: 1.3724584579467773
    median: -0.013500070665031672
    iqr: 0.47064224630594254