dataset_name: KuramotoSivashinsky
dataset_directory_path: ./data/fluids/KS/2D
dimension: 2
in_channels: null #if not provided, will be computed inferred from the filter_channels
out_channels: null #if not provided, will be computed inferred from the filter_channels
sequence_info: [4, 3, 2]
filter_frame: null 
filter_groups: null
filter_channels: null 
grid_resolution: null #if not provided, will be inferred automatically from the dataset
data_normalization_stats: null #if not provided, will be computed automatically from the dataset
data_normalization_strategy: z_normalization #options: z_normalization, min_max_normalization