# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: KuramotoSivashinsky
dataset_directory_path: ./data/fluids/KS/2D
dimension: 2
grid_resolution: null 
eval_groups: null
is_steady_state_prediction: False
sequence_info: [3, 1, 1]
filter_frames: null 
filter_groups: null
# available channels for KS: ['velocity']
filter_in_channels: null
filter_out_channels: null
conditioning_in_channels: null
#NOTE: For transient simulations, filter_in_channels = filter_out_channels + conditioning_in_channels
include_conditioning_parameters: False
residual_config: null
  # add_base_value_with_raw_loss: True
  # add_predicted_value_with_diff_loss: False
  # add_predicted_value_with_raw_loss: False
data_normalization_stats: null
data_normalization_strategy: z_normalization