dataset_name: KuramotoSivashinsky
dataset_directory_path: ./data/fluids/KS/3D
dimension: 3
sequence_info: [4, 3, 2]  # [input_seq_len, label_seq_len, stride]
filter_frames: [10, 50]  # [min_frame, max_frame]
filter_groups: null
filter_in_channels: null
filter_out_channels: null
conditioning_in_channels: null
include_conditioning_parameters: False
residual_config:
  add_base_value: False
  add_predicted_value: True
is_steady_state_prediction: False #assuming the last frame is the steady state
grid_resolution: null #if not provided, will be inferred automatically from the dataset
data_normalization_stats: null #if not provided, will be computed automatically from the dataset
data_normalization_strategy: z_normalization #options: z_normalization, min_max_normalization
eval_groups: null