defaults:
  - data_config: fluids/KS/2d_ks_data_default
  - model_config: UNet/default_unet
  - output_log_config: default_output_log
  - scheduler_config: default_scheduler
  - train_config: default_training
  - infer_config: default_infer
  - hyperparam_opt_config: default_hp_config
  - train_strategy_config: default_train_strategy
  - _self_