defaults:
  - data_config: KVS/default_kvs_data
  - model_config: FNO/default_fno
  #- output: default_output
  - scheduler_config: default_scheduler
  - train_config: default_training
  - infer_config: default_infer
  #- hydra: default_hydra_config
  - _self_

#gpu_id: 0   #remove this later and find a suitable way to set this
