model_name: FFNO

# Core architecture
latent_channels: 96
n_fno_layers: 8
fno_modes: 20  # can also be a list for ND, e.g. [16, 16] or [16, 16, 16]

# FFNO block settings
factor: 4
n_ff_layers: 2
layer_norm: true

# Framework-level normalization fields
norm_layer_eps: 1e-5
norm: 'layer' # layer, batch, group, identity