dataset_name: KarmanVortexStreet
dataset_directory_path: ./data/fluids/KVS/2D_trimmed
dimension: 2
in_channels: 3 #rho ,u ,v
out_channels: 3
sequence_info: [4, 3, 1]
filter_frame: null #filter_frame: [100, 500]
filter_groups: null #filter_groups: ["Re_100", "Re_300", "Re_400"]
filter_fields: null #filter_fields: ["velocity", "density"]
grid_resolution: [256,64]