#To intall the dependencies from this file: 
#conda env create -f environment.yml
## comment out the lines starting with nvidia* if there is no nvidia-GPU
name: neptuna_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - jedi
  - jupyter_client
  - jupyter_core
  - ld_impl_linux-64
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - python=3.13.1
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - tzdata
  - wcwidth
  - wheel
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xorgproto
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - alembic
      - annotated-types
      - antlr4-python3-runtime
      - attrs
      - blessed
      - certifi
      - charset-normalizer
      - click
      - colorlog
      - contourpy
      - cycler
      - filelock
      - fonttools
      - frozenlist
      - fsspec
      - gitdb
      - gitpython
      - greenlet
      - h5py
      - huggingface-hub
      - hydra-core
      - idna
      - imageio
      - imageio-ffmpeg
      - jinja2
      - kiwisolver
      - lazy-loader
      - lightning
      - lightning-utilities
      - mako
      - markupsafe
      - matplotlib
      - mpmath
      - multidict
      - networkx
      - numpy
      # Comment out the following lines if you don't have a GPU
      #--------------------------------------------------------
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-cusparselt-cu12
      - nvidia-ml-py
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      #--------------------------------------------------------
      - omegaconf
      - optuna
      - pillow
      - propcache
      - protobuf
      - pydantic
      - pydantic-core
      - pyparsing
      - pytorch-lightning
      - pyyaml
      - regex
      - requests
      - safetensors
      - scikit-image
      - scipy
      - sentry-sdk
      - setproctitle
      - smmap
      - sqlalchemy
      - sympy
      - tifffile
      - tokenizers
      - torch==2.10.0
      - torchmetrics
      - tqdm
      - transformers==4.56.0
      - triton
      - typing-extensions
      - typing-inspection
      - urllib3
      - wandb
      - yarl
      - ptwt==1.0.1
      - pykeops==2.3
      - watchdog==6.0.0
