optimize: true
n_trials: 4
metric_for_tuning_hp: ['eval_l2_error', 'eval_l1_error']
search_space:
#only the arguments as mentioned in TrainingArguments can be done for HP Optimization

  # num_train_epochs:
  #   method: categorical
  #   choices: [0.06, 0.07]
  train_config:
    max_steps:
      method: categorical
      choices: [10, 15]

    pushforward:
      max_allowed_unroll_steps:
        method: categorical
        choices: [[1,1,1], [0,1,3]]


  data_config:
    # sequence_info:
    #   method: categorical
    #   choices: [[3, 2, 1]]
    
    filter_frames:
      method: categorical
      choices: [[null, null], [10, 49]]

    data_normalization_strategy:
      method: categorical
      choices: ["z_normalization", "min_max_normalization"]
