optimize: true
n_trials: 5
metric_for_tuning_hp: ['eval_l2_error']
optuna_sampler: TPESampler
sampler_params:
  n_startup_trials: 10
  seed: 42
search_domain:
  train_config:
    num_train_epochs:
      method: categorical
      choices: [0.05, 0.1]

    pushforward_config:
      max_allowed_unroll_steps:
        method: categorical
        choices: [[0,0,0]]
    
  model_config:
    latent_channels:
      method: categorical
      choices: [16, 32, 64]
    cno_depth:
      method: categorical
      choices: [2, 3, 4]
    n_blocks:
      method: categorical
      choices: [4,5]
    n_blocks_bottleneck:
      method: categorical
      choices: [2, 4]
    channel_multiplier:
      method: categorical
      choices: [8, 16, 32]
    norm:
      method: categorical
      choices: [True, False]