optimize: true
n_trials: 200
metric_for_tuning_hp: ['eval_l2_error']
search_space:
  train_config:
    max_steps:
      method: categorical
      choices: [25]

    pushforward:
      max_allowed_unroll_steps:
        method: categorical
        choices: [[0,0,0]]

  model_config:
    latent_channels:
      method: categorical
      choices: [16, 32, 64]
    n_fno_layers:
      method: categorical
      choices: [2, 3, 4]
    decoder_layers:
      method: categorical
      choices: [1, 2, 3]
    decoder_layer_size:
      method: categorical
      choices: [64, 128, 256]