do_infer: True
load_best_model_at_end: False
n_infer_rollouts: 9
n_infer_plot_examples: 2
inference_directory: ./checkpoints
filter_features:
  infer_filter_frames: [null, null]
  infer_filter_groups: null 
infer_from_random_timestep: False
infer_from_ic: True