do_infer: True
inference_directory: ./sample_inference/infer_loss_test
dataset_directory_path: ./data/fluids/KS/1D  # if null, will use the dataset_directory_path from data_config.json inside the experiment directory.
filter_features:
  infer_filter_frames: [null, null]
  infer_filter_groups: null
n_infer_rollouts: 2
n_infer_plot_examples: 2
infer_from_random_timestep: False
infer_from_ic: True