model_name: ScOT
patch_size: 8 # patch embedding resolution: resolution/patch_size -> padding if not divisible
latent_channels: 48
depths: [4, 4]
num_heads: [3, 6, 12, 24]
skip_connections: [2, 2, 2, 0]
window_size: 16 # (window_size - patch_embedding_resolution % window_size) % window_size -> padding before window-based self-attention
mlp_ratio: 4.0
qkv_bias: True
hidden_dropout_prob: 0.0
attention_dropout_prob: 0.0
drop_path_rate: 0.0
hidden_act: "gelu"
use_absolute_embeddings: False
initializer_range: 0.02
residual_model: "convnext" # convnext or resnet
