train_loss:
  components:
    - type: L2Loss
      weight: 0.5
    - type: SSIM
      weight: 0.5
    - type: ShockRMSE
      weight: 1.0
  train_loss_weighting_strategy:
    enabled: false  # Set to true to enable
    type: BalancedResidualDecayRate
    loss_source: 'train' # 'train', 'eval' or 'both'
  
validation_loss:
  components:
    - type: L1Loss
      weight: 1.0
    - type: CompositeLoss
      weight: 1.0
      name: "SSIM_L2_Composite"
      sub_components:
        - type: SSIM
          weight: 0.7
        - type: L2Loss
          weight: 0.3



# Each component is a dictionary with the following fields.
# Mandatory:
# - type: Name of the loss class (see metrics/losses)
# Optional:
#   name: Custom name for the loss component
#   config_file: Custom path to a config file for the loss component
#   weight: Base scalar weight (default: 1.0)
#   timestep_weights: List of per-timestep weights, length T (optional)
#   channel_weights: List of per-channel weights, length C (optional)

# Composite metrics can be defined for validation/inference using the type 
# "CompositeLoss" and specifying the components as "sub-components".

# Example: RMSE with per-channel weighting
# - type: RMSE
#   weight: 1.0
#   channel_weights: [1.0, 1.0, 0.5]

# Example: RMSE/L2 composite eval loss
# - type: CompositeLoss
#   weight: 1.0
#   name: "SSIM_L2_Composite"
#   sub_components:
#     - type: SSIM
#       weight: 0.7
#     - type: L2Loss
#       weight: 0.3

