loss:
  components:
    - type: NRMSE
      weight: 0.5
      timestep_weights: [1.0]
      channel_weights: [1.0]
    - type: L1Loss
      weight: 1.0
      timestep_weights: [1.0]
      channel_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
