loss:
  components:
    - type: L2Loss
      weight: 0.0
      name: mse
      config_file: L2_Loss/l2_loss_default
    - type: SinkhornDivergence
      weight: 0.5
      name: sinkhorn_divergence
      config_file: SinkhornDivergence/sinkhorn_divergence_default