# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: SyntheticFlow
seed: 42
dataset_directory_path: ./data/synthetic/SF/2D/constant
dimension: 2
grid_resolution: null 
eval_groups: null
is_steady_state_prediction: False 
sequence_info: [4, 3, 2]
# available: ['density','schlieren','velocity'] OR ['density','schlieren','velocity_0','velocity_1']
filter_features:
  train_filter_frames: [0, 75]
  train_filter_groups: null
  infer_filter_frames: [0, 75]
  infer_filter_groups: null
  filter_in_channels: ['density','schlieren','velocity'] 
  filter_out_channels: ['density','velocity']
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
conditioning_features:
  conditioning_in_channels: ['schlieren']
  include_conditioning_parameters: False
  parameter_min_max_stats: null
residual_config: null
  # add_base_value_with_raw_loss: True
  # add_predicted_value_with_diff_loss: False
  # add_predicted_value_with_raw_loss: False
data_normalization_stats: null
data_normalization_strategy: z_normalization #z_normalization, min_max_normalization, robust_normalization