# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: LaserDroplet
dataset_directory_path: /local/disk1/szehisaadat/MainRepos/Neptuna/data/fluids/LaserDroplet/2D
seed: 42
dimension: 2
grid_resolution: null
eval_groups: null
is_steady_state_prediction: False 
sequence_info: [5, 4, 5]
# Available channels for LaserDroplet: ["Pressure", "Energy", "Density", "Velocity_X", "Velocity_Y", "Schlieren"]
filter_features:
  train_filter_frames: null
  train_filter_groups: null
  infer_filter_frames: null
  infer_filter_groups: null
  filter_in_channels: ["Density", "Pressure"]
  filter_out_channels: ["Density","Pressure"]
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
conditioning_features:
  conditioning_in_channels: null #support deprecated
  conditioning_method: null # AdaNorm_LSE AdaNorm_SE_per_param AdaNorm_1SE AdaNorm null
  conditioning_parameter_names: null # e.g. ["Mas", "ugasf", "We"]; null means use all parsed parameters
  parameter_min_max_stats: null
  conditioning_mlp:
    mlp: False
    hidden_size: null
    activation: gelu
    initialization: null
residual_config: null
  # add_base_value_with_raw_loss: True
  # add_predicted_value_with_diff_loss: False
  # add_predicted_value_with_raw_loss: False
coord_features: True
log_transform_channels: []
data_normalization_strategy: z_normalization
#NOTE: Statistics are according to sequence_stride = 1
data_normalization_stats:
  Density:
    mean: 67.95441809384442
    std: 244.57315988714203
    min: 0.04284508956123448
    max: 1427.2889686958108
  Energy:
    mean: 68584806.65496126
    std: 305666902.09644586
    min: 101499.8765581337
    max: 29859812636.182396
  Pressure:
    mean: 7080948.396527351
    std: 98072020.67400207
    min: -584609247.259088
    max: 9853244989.408216
  Schlieren:
    mean: 37779010.432428166
    std: 322792042.74342763
    min: 0.0
    max: 29785076199.65439
  Velocity_X:
    mean: 222.12469629090495
    std: 439.2046025229817
    min: -1484.035009764289
    max: 6897.916526253297
  Velocity_Y:
    mean: 437.9463497449755
    std: 935.0255611736854
    min: -1375.342835865244
    max: 10103.253292198731