# For details on the parameters, refer to data_config-->example_data_config.yaml
dataset_name: LaserDroplet
dataset_directory_path: /local/disk/szehisaadat/Neptuna/data/fluids/LaserDroplet/2D
seed: 42
dimension: 2
grid_resolution: null
eval_groups: null
is_steady_state_prediction: False 
sequence_info: [1, 1, 1]
# Available channels for LaserDroplet: ["Pressure","Density", "Schlieren"]
filter_features:
  train_filter_frames: null
  train_filter_groups: null
  infer_filter_frames: null
  infer_filter_groups: null
  filter_in_channels: null
  filter_out_channels: null
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
conditioning_features:
  conditioning_in_channels: null
  include_conditioning_parameters: False
  num_cond_params: null
  parameter_min_max_stats: null
residual_config: null
#   add_base_value_with_raw_loss: False
#   add_predicted_value_with_diff_loss: True
#   add_predicted_value_with_raw_loss: False
coord_features: True
data_normalization_strategy: z_normalization
data_normalization_stats: 
  Density: 
    mean: 69.15749838331831
    std: 246.92007530374036
    min: 0.04284508956123448
    max: 1390.0990886807508
  Pressure: 
    mean: 6447089.847962431
    std: 83512064.37223315
    min: -574292266.7745304
    max: 7548400000.000001
  Schlieren: 
    mean: 36828740.39687321
    std: 321071308.16520864
    min: 0.0
    max: 46219090641.15646