dataset_name: LaserDroplet
dataset_directory_path: ./data/fluids/Laser_Droplet/2D
dimension: 2
grid_resolution: null
eval_groups: null
is_steady_state_prediction: False 
sequence_info: [1, 1, 1]
filter_frames: null 
filter_groups: null
# Available channels for LaserDroplet: ["Pressure", "Energy", "Density", "Velocity_X", "Velocity_Y"]
filter_in_channels: null
filter_out_channels: null
conditioning_in_channels: null
#NOTE: For transient simulations, filter_in_channels = filter_out_channels+conditioning_in_channels
include_conditioning_parameters: True
residual_config: null
#   add_base_value_with_raw_loss: False
#   add_predicted_value_with_diff_loss: True
#   add_predicted_value_with_raw_loss: False
data_normalization_stats: null
data_normalization_strategy: z_normalization