dataset_name: KarmanVortexStreet
dataset_directory_path: ./data/fluids/KVS/2D
sequence_info: [[6, 7, 1, 1]]
filter_frame: null #filter_frame: [[100, 500]]
filter_groups: null #filter_groups: ["Re_100", "Re_300", "Re_400"]
filter_fields: null #filter_fields: ["velocity", "density"]